---
# Pi-hole configuration.
pihole_enable: true
pihole_hostname: das-pihole
pihole_timezone: Pacific/Auckland
pihole_password: pokemon

# Internet monitoring configuration.
monitoring_enable: true

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: password

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
