---
- name: Clone shelly-plug-prometheus repo to Pi.
  ansible.builtin.git:
    repo: https://github.com/geerlingguy/shelly-plug-prometheus
    dest: ~/shelly-plug-prometheus/
    version: master
    accept_hostkey: true
  become: false

- name: Copy Shelly Plug docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/shelly-plug-docker-compose.yml.j2
    dest: ~/shelly-plug-prometheus/docker-compose.yml
    mode: '0640'
  become: false

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Shelly Plug Prometheus exporter is running.
  community.docker.docker_compose:
    project_src: ~/shelly-plug-prometheus/
    build: false
  become: false
