---
- name: Ensure Starlink directory exists.
  file:
    path: ~/starlink-exporter
    state: directory
    mode: 0755
  become: false

- name: Copy Starlink docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/starlink-docker-compose.yml.j2
    dest: ~/starlink-exporter/docker-compose.yml
    mode: '0640'
  become: false

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Starlink Prometheus exporter is running.
  community.docker.docker_compose:
    project_src: ~/starlink-exporter/
    build: false
  become: false
